Add http response code checking/reporting to curl::multi::run
tenzir/tenzir pull request #4660
Opened 2024-10-11 11:20 UTC by IyeOnline

This solves issues with the http loader successfully yielding a 404 page without an error report.

2024-10-11 13:19 UTC, mavam requested changes
The check might do what it's supposed to, but it's at the wrong location. Since cURL is a multi-protocol tool, this check must only be performed in the case where we actually got a (HTTP) response code.

Let's discuss where this would be better.

2024-10-11 13:19 UTC, mavam commented on libtenzir/src/curl.cpp
> +    curl_easy_getinfo(msg->easy_handle, CURLINFO_RESPONSE_CODE, &response_code);
I think you need to check the return code and perform the subsequent response code check only after you got `code::ok`.

2024-10-15 07:01 UTC, mavam commented
@IyeOnline I orthogonalized the curl and transfer abstractions again, keeping the former just as an unopinionated wrapper and the latter the thing where we opine.

(I didn't get a chance to test this yet, though, as I'm still traveling. Mind giving it a try?)

2024-10-15 07:05 UTC, mavam approved these changes
The response logic itself is fine. I moved it to a different location, though.

(Self-approving modulo testing.)

2024-10-15 09:02 UTC, dominiklohmann commented on libtenzir/src/curl.cpp
> +  // case.
This looks like it still needs to be done.

2024-10-15 09:02 UTC, dominiklohmann commented on libtenzir/src/curl.cpp
> +  __builtin_unreachable();
```suggestion
  TENZIR_UNREACHABLE();
```

2024-10-15 09:02 UTC, dominiklohmann commented on libtenzir/src/transfer.cpp
> +                                               response_code));
This should use `diagnostic::error(…).to_error()` like all new code.

2024-10-15 09:02 UTC, dominiklohmann commented on libtenzir/include/tenzir/curl.hpp
> +  using info_data = std::variant<bool, long, std::string_view>;
The comment should really explain what it means to get a bool, long, or string view, respectively.

2024-10-16 07:36 UTC, merged