Add OpenSearch integration page
tenzir/tenzir pull request #4873
Opened 2024-12-19 15:07 UTC by mavam

This PR adds a new integration page for OpenSearch

2024-12-19 21:22 UTC, lo-chr requested changes
Just a little typo.

2024-12-19 21:22 UTC, lo-chr commented on web/docs/integrations/opensearch/README.md
> +The above example udpates the document with ID 42 with the contents from the
"udpates" -> "updates"
```suggestion
The above example updates the document with ID 42 with the contents from the
```

2024-12-20 03:33 UTC, raxyte commented on web/docs/integrations/opensearch/README.md
> +The above example udpates the document with ID 42 with the contents from the
```suggestion
The above example udpates the document with ID `XXX` with the contents from the
```

2024-12-20 16:10 UTC, dominiklohmann approved these changes
I gave this a quick spin with my local OpenSearch instance, and the provided pipelines appear to work as expected.

🙏

2024-12-20 16:12 UTC, merged